# Generated by Django 2.1.5 on 2019-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0003_auto_20190425_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Company',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='Data_field',
            field=models.CharField(blank=True, choices=[('A', '발전사 동향'), ('B', '전력산업/시장'), ('C', '신재생에너지/기술'), ('D', '경제'), ('E', '에너지')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='Published_date',
            field=models.DateField(default=None),
        ),
    ]
