# Generated by Django 2.2.4 on 2020-07-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0004_auto_20190425_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='Comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MorningBriefing.Comment'),
        ),
    ]
