# Generated by Django 2.2.4 on 2020-07-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0005_auto_20200705_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MorningBriefing.Comment'),
        ),
    ]
