# Generated by Django 3.0.4 on 2020-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0007_auto_20200706_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Importance',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
