# Generated by Django 3.0.4 on 2020-07-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MorningBriefing', '0008_news_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['Data_field', 'Published_date', 'Importance']},
        ),
    ]
